// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class Gangwar
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public string Name { get; set; }
        public float Size { get; set; }
        public int Type { get; set; }
        public DateTime LastAttack { get; set; }
        public float MiddlePositionX { get; set; }
        public float MiddlePositionY { get; set; }
        public float MiddlePositionZ { get; set; }
        public float AttackPositionX { get; set; }
        public float AttackPositionY { get; set; }
        public float AttackPositionZ { get; set; }
        public float RewardPositionX { get; set; }
        public float RewardPositionY { get; set; }
        public float RewardPositionZ { get; set; }
        public float Flag1PositionX { get; set; }
        public float Flag1PositionY { get; set; }
        public float Flag1PositionZ { get; set; }
        public float Flag2PositionX { get; set; }
        public float Flag2PositionY { get; set; }
        public float Flag2PositionZ { get; set; }
        public float Flag3PositionX { get; set; }
        public float Flag3PositionY { get; set; }
        public float Flag3PositionZ { get; set; }

        public virtual Team Team { get; set; }
    }
}