// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class Inventory
    {
        public Inventory()
        {
            InventoryItems = new HashSet<InventoryItem>();
            PlayerInventories = new HashSet<PlayerInventory>();
        }

        public int Id { get; set; }
        public int InventoryTypeId { get; set; }
        public int TargetId { get; set; }

        public virtual InventoryType InventoryType { get; set; }
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
        public virtual ICollection<PlayerInventory> PlayerInventories { get; set; }
    }
}