// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class InventoryItem
    {
        public int Id { get; set; }
        public int InventoryId { get; set; }
        public int ItemId { get; set; }
        public int Amount { get; set; }
        public int Slot { get; set; }

        public virtual Inventory Inventory { get; set; }
        public virtual Item Item { get; set; }
    }
}