// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class InventoryType
    {
        public InventoryType()
        {
            Inventories = new HashSet<Inventory>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public string DisplayName { get; set; }
        public int MaxWeight { get; set; }
        public int MaxSlots { get; set; }

        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}