// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class Item
    {
        public Item()
        {
            InventoryItems = new HashSet<InventoryItem>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int MaxStack { get; set; }
        public int Weight { get; set; }
        public string CustomDataText { get; set; }

        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
    }
}