// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class Player
    {
        public Player()
        {
            PlayerCharacters = new HashSet<PlayerCharacter>();
            PlayerInventories = new HashSet<PlayerInventory>();
            PlayerTeamInfos = new HashSet<PlayerTeamInfo>();
            PlayerWeapons = new HashSet<PlayerWeapon>();
            Vehicles = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public string CharacterName { get; set; }
        public string Password { get; set; }
        public string Serial { get; set; }
        public string SocialclubName { get; set; }
        public int Money { get; set; }
        public bool Injured { get; set; }
        public float PositionX { get; set; }
        public float PositionY { get; set; }
        public float PositionZ { get; set; }
        public DateTime CreatedAt { get; set; }

        public virtual ICollection<PlayerCharacter> PlayerCharacters { get; set; }
        public virtual ICollection<PlayerInventory> PlayerInventories { get; set; }
        public virtual ICollection<PlayerTeamInfo> PlayerTeamInfos { get; set; }
        public virtual ICollection<PlayerWeapon> PlayerWeapons { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}