// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class PlayerInventory
    {
        public int Id { get; set; }
        public int InventoryId { get; set; }
        public int PlayerId { get; set; }

        public virtual Inventory Inventory { get; set; }
        public virtual Player Player { get; set; }
    }
}