// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class PlayerCharacter
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        /// <summary>
        /// JSON a la Phill
        /// </summary>
        public string Customization { get; set; }

        public virtual Player Player { get; set; }
    }
}