// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class TeamInfo
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int WeaponPackets { get; set; }

        public virtual Team Team { get; set; }
    }
}