// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public int GarageId { get; set; }
        public int OwnerId { get; set; }
        public int TeamId { get; set; }
        public bool Parked { get; set; }

        public virtual Garage Garage { get; set; }
        public virtual Player Owner { get; set; }
        public virtual Team Team { get; set; }
    }
}