// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

// made by Dschahannam.
namespace Sibaui.Database.Entities
{
    public partial class Weapon
    {
        public Weapon()
        {
            TeamHideoutWeapons = new HashSet<TeamHideoutWeapon>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public uint WeaponHash { get; set; }
        public int MaxAmmo { get; set; }

        public virtual ICollection<TeamHideoutWeapon> TeamHideoutWeapons { get; set; }
    }
}